version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mapmyworld
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres+psycopg2://postgresql:1234@db/mapmyworld

volumes:
  postgres-data: